apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  namespace: iona-console
  name: iona-app
spec:
  targetNamespace: iona-console
