apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # metadata is used to match the target to patch
  namespace: iona-console
  name: iona-app
spec:
  images:
    - name: iona-app
      newName: eu.gcr.io/iona-1/iona-app
      newTag: main-latest  # {"$imagepolicy": "iona-console:iona-app-main:tag"}

