apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "cert-wild-iona-thaumagen-io"
spec:
  commonName: "iona.thaumagen.io"
  secretName: cert-wild-iona-thaumagen-io
  dnsNames:
    - "iona.thaumagen.io"
    - "*.iona.thaumagen.io"
  issuerRef:
    name: letsencrypt-prod-primary-dns
    kind: ClusterIssuer
