---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: iona-app
  namespace: iona-console
spec:
  interval: 5m
  image: eu.gcr.io/iona-1/iona-app
  secretRef:
    name: regcred
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: iona-app-main
  namespace: iona-console
spec:
  imageRepositoryRef:
    name: iona-app
  filterTags:
    # pattern: '^main-[a-f0-9]+-[0-9]+.[0-9]+.(?P<monotonic>[0-9]+)'
    pattern: '^main-(?P<monotonic>.+)'
    extract: '$monotonic'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: imageupdates
  namespace: iona-console
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: iona-console
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: .
    strategy: Setters
