---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: iona-app
  namespace: iona-console
spec:
  interval: 5m
  image: eu.gcr.io/iona-1/iona-app
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          kubernetes.io/metadata.name: flux-system
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: iona-app-main
  namespace: iona-console
spec:
  imageRepositoryRef:
    name: iona-app
  filterTags:
    # pattern: '^main-[a-f0-9]+-[0-9]+.[0-9]+.(?P<monotonic>[0-9]+)'
    pattern: '^main-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iona-console-push
  namespace: iona-console
spec:
  interval: 30s
  url: ssh://git@github.com/thaumagen/fluxcd-iona-console.git
  ref:
    branch: main
  secretRef:
    name: fluxcd-iona-console

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: imageupdates
  namespace: iona-console
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: iona-console-push
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: .
    strategy: Setters
