---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: iona-app
spec:
  interval: 5m
  image: eu.gcr.io/iona-1/iona-app
  accessFrom:
    namespaceSelectors:
      - matchLabels:
          # XXX: TODO not sure why this is flux-system rather than iona-console
          kubernetes.io/metadata.name: flux-system
---
# We probably need to have a specific one for each of staging/prod/dev
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: iona-app-main
spec:
  imageRepositoryRef:
    name: iona-app
  filterTags:
    # pattern: '^main-[a-f0-9]+-[0-9]+.[0-9]+.(?P<monotonic>[0-9]+)'
    pattern: '^main-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: imageupdates
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: fluxcd-iona-console
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: .
    strategy: Setters
