apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./sync.yaml
  - ./certificate.yaml
patchesJson6902:
  - target:
      kind: IngressRoute
      name: iona-app
    path: patch-ingressroute.yaml
  - target:
      kind: Middleware
      name: strip-ingressroute-prefix
    path: patch-middleware-stripprefix-ingressroute.yaml
