---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iona-app
spec:
  interval: 30s
  prune: true
  url: https://github.com/robinbryce/iona-app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
  #name: iona-app
  #namespace: iona-console
spec:
  interval: 30s
  path: ./k8s/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iona-app
