---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iona-app
spec:
  interval: 1m0s
  prune: true
  url: https://github.com/robinbryce/iona-app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: iona-app
spec:
  interval: 1m0s
  prune: true
  sourceRef:
    kind: GitRepository
    name: iona-app
  path: ./k8s/app
