---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iona-app
spec:
  interval: 30s
  url: https://github.com/robinbryce/iona-app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  namespace: iona-console
  name: iona-app
spec:
  interval: 30s
  path: ./k8s/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iona-app
  patches:
    - target:
        kind: IngressRoute
        name: iona-app
      patch: |-
             - op: replace
               path: /spec/routes/0/match
               value: Host(`iona.thaumagen.io`) && PathPrefix(`/console2/`)
             - op: replace
               path: /spec/tls/secretName
               value: wild-iona-thaumagen-io
    - target:
        kind: Middleware
        name: strip-ingressroute-prefix
      patch: |-
             - op: replace
               path: /spec/stripPrefix/prefixes/0
               value: /console2/
