---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: iona-app
spec:
  interval: 30s
  url: https://github.com/robinbryce/iona-app
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: iona-app
spec:
  interval: 30s
  path: ./k8s/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: iona-app
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: iona-app
        spec:
          template:
            spec:
              containers:
                - name: service
                  image: iona-app
                  env:
                    - name: NODE_PATH
                      value: stage/node
                    - name: CHAIN_PROVIDER_PATH
                      value: stage/chain1
