apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-iona-console
resources:
  - ../base
patchesStrategicMerge:
  # patch our git source reference to apply targetNamespace
  - secret-iona-console-image-automationsealed.yaml
  - patch-targetnamespace.yaml
  - patch-image-automation.yaml
  - patch-ingressroutes.yaml
