apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-iona-console
resources:
  - ../base
  - secret-iona-console-image-automationsealed.yaml
patchesStrategicMerge:
  - patch-targetnamespace.yaml
  - patch-image-automation.yaml
  - patch-ingressroutes.yaml
  - patch-deployment-env.yaml
