apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage-iona-console
resources:
  - ../base
  - secret-iona-console-image-automationsealed.yaml
patchesStrategicMerge:
  - patch-targetnamespace.yaml
  - patch-image-automation.yaml
  # - patch-ingressroutes.yaml
  # - patch-deployment-env.yaml
patchesJson6902:
  # To apply multiple patches to the same list we *have* to use Json6902
  - target:
      kind: Kustomization
      version: kustomize.toolkit.fluxcd.io/v1beta2
      name: iona-app
    path: patch-ingressroutes.yaml
  - target:
      kind: Kustomization
      version: kustomize.toolkit.fluxcd.io/v1beta2
      name: iona-app
    path: patch-deployment-env.yaml


