- op: add
  path: /spec/patches/-
  value:
    patch:
      target:
        kind: Deployment
        name: iona-app
      patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: iona-app
        spec:
          template:
            spec:
              containers:
                - name: service
                  image: iona-app
                  env:
                    - name: NODE_PATH
                      value: stage/node
                    - name: CHAIN_PROVIDER_PATH
                      value: stage/chain1

#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: iona-app
#spec:
#  patches:
#    - target:
#        kind: Deployment
#        name: iona-app
#      patch: |-
#        apiVersion: apps/v1
#        kind: Deployment
#        metadata:
#          name: iona-app
#        spec:
#          template:
#            spec:
#              containers:
#                - name: service
#                  image: iona-app
#                  env:
#                    - name: NODE_PATH
#                      value: stage/node
#                    - name: CHAIN_PROVIDER_PATH
#                      value: stage/chain1
#
